RADIUS_DATA_BUBBLE = 150; // In meters, in order to increase precision
RADIUS_NEAR_BUBBLE = 50;
DISTANCE_MULTIPLIER_METERS = 6378137; // Earth radius in meters
RADIUS_TOTAL = RADIUS_DATA_BUBBLE + RADIUS_NEAR_BUBBLE;

exports.DEFAULT_PORT = 3000;
exports.DISTANCE_MULTIPLIER_METERS = DISTANCE_MULTIPLIER_METERS;
exports.CODE_SUCCESS = 0;
exports.CODE_ERROR = 1;
exports.CODE_ERROR_MISSING_PARAMETER = 2;
exports.RADIUS_DATA_BUBBLE = RADIUS_DATA_BUBBLE;

// In MongoDB, legacy coordinates are being used, thus convert maxDistance
// to radians
exports.RADIUS_DATA_BUBBLE_WITH_PROXIMITY = RADIUS_TOTAL / DISTANCE_MULTIPLIER_METERS;
